FROM python:3.14.2-slim

COPY requirements_migration.txt ./requirements_migration.txt

RUN pip install -r requirements_migration.txt

COPY source/alembic.ini .

COPY source/settings.py ./settings.py

COPY source/database ./database

CMD ["sh", "-c", "alembic upgrade head"]
